'use client'

import React from 'react'
import ProjectDetail from '@/app/components/ProjectDetail'
import CRMThumbnail from '@/app/components/CRMThumbnail'

export default function ConsultingReportsMonitorPage() {
  return (
    <ProjectDetail
      title="Consulting Reports Monitor"
      image="/assets/projects/consulting-reports-monitor.svg"
      customThumbnail={<CRMThumbnail />}
      projectLength="Personal project · Ongoing"
      context="Staying current on McKinsey and BCG publications is a recurring challenge for strategy and consulting professionals. Reports are scattered across multiple sectoral pages and sitemaps, and there is no unified, automated way to be notified when new insights are published. Reading each report in full is time-consuming; a structured AI summary would make the intelligence immediately actionable."
      objective="Build a fully automated, zero-intervention pipeline that discovers new McKinsey (8 sectors) and BCG (13 themes) publications, enriches them with full article text and PDFs, generates a structured ~1,200-word French summary via generative AI, and delivers one HTML email per new report. Once configured, no human action is required."
      implementation="Designed and built a TypeScript monorepo with a modular adapter architecture: McKinsey discovery via RSS feeds and HTML scraping of sectoral insight pages; BCG discovery via the public sitemap XML filtered to the current year. The pipeline runs bi-weekly on GitHub Actions at zero infrastructure cost using free-tier AI (Gemini 2.0 Flash or Groq Llama 3.3 70B) and Gmail SMTP."
      method={`The pipeline executes four sequential stages:

1. Discovery — Source adapters fetch new publications from McKinsey (RSS/HTML) and BCG (sitemap XML). URLs are canonicalized and deduplicated against the SQLite database.

2. Enrichment — Each new item is fetched (HTML article + PDF if detected) and cleaned. A SHA-256 content hash provides a second deduplication layer resistant to URL changes.

3. Summarization — The enriched text is passed to the configured AI provider (Gemini, Groq, or OpenAI). A structured prompt produces a 9-section French summary: TL;DR, key insights, context, results, data/signals, strategic implications, sector relevance, conclusion, and source link.

4. Delivery — One HTML email per publication is sent via Nodemailer. State is persisted in SQLite (discovered → summarized → emailed) enabling automatic retry of failed items on the next run.`}
      result="A fully operational intelligence pipeline running at 0 €/month. Bi-weekly GitHub Actions cron (Monday + Thursday, 7h UTC) covers McKinsey and BCG publications across 21 sectors and themes. The two-level deduplication (canonical URL + content hash) prevents duplicate emails even when publishers update URLs. A failed run mid-pipeline automatically resumes from the last successful state on the next execution."
      tools={[
        'Node.js / TypeScript',
        'GitHub Actions',
        'Prisma / SQLite',
        'Gemini 2.0 Flash',
        'Groq Llama 3.3 70B',
        'Nodemailer / SMTP',
        'HTML Scraping',
        'Sitemap XML',
        'Zod',
        'pino',
      ]}
      screenshots={[
        {
          title:       'Email Header & TL;DR',
          image:       '/assets/projects/screenshots/crm-header.png',
          description: 'Each email opens with source attribution (McKinsey · Intelligence Report), the report title, sector tag, publication date, reading time estimate, and a one-paragraph TL;DR generated by the AI.',
        },
        {
          title:       'Key Insights — structured bullets',
          image:       '/assets/projects/screenshots/crm-key-insights.png',
          description: 'Section 02 extracts the 4–6 most actionable findings as concise bullet points, allowing the reader to assess relevance in under 30 seconds.',
        },
        {
          title:       'Context & Central Arguments',
          image:       '/assets/projects/screenshots/crm-context.png',
          description: 'Sections 03 and 04 provide the structural context of the report and its central thesis, synthesised from the full article and PDF when available.',
        },
        {
          title:       'Data, Signals & Strategic Implications',
          image:       '/assets/projects/screenshots/crm-data.png',
          description: 'Section 05 surfaces hard numbers and weak signals. Section 06 translates findings into strategic implications for senior decision-makers.',
        },
        {
          title:       'Conclusion & Source Link',
          image:       '/assets/projects/screenshots/crm-conclusion.png',
          description: 'Section 08 synthesises the McKinsey/BCG recommendation framework. Section 09 provides the canonical source URL, and the CTA button links directly to the original report.',
        },
      ]}
    />
  )
}
